playground:
  outputs:
    dev:
      type: sqlite
      threads: 1
      database: "{{ env_var('DB_NAME') }}"
      schema: "{{ env_var('DB_SCHEMA') }}"
      schemas_and_paths:
        main: "{{ env_var('DBT_PROFILES_DIR') }}/{{ env_var('DB_NAME') }}"
      schema_directory: "{{ env_var('DBT_PROFILES_DIR') }}"

    prod:
      type: sqlite
      threads: 1
      database: "{{ env_var('DB_NAME') }}"
      schema: "{{ env_var('DB_SCHEMA') }}"
      schemas_and_paths:
        main: "{{ env_var('DBT_PROFILES_DIR') }}/{{ env_var('DB_NAME') }}"
      schema_directory: "{{ env_var('DBT_PROFILES_DIR') }}"
